<?php

namespace frontend\models;

use yii\db\ActiveRecord;

class Person2 extends ActiveRecord
{
    public static function tableName()
    {
        return 'person';
    }

    public function rules()
    {
        return [
            [['firstname'], 'string'],
            [['gender'], 'integer'],
            [['firstname', 'gender'], 'required'],
        ];
    }

    public function beforeSave($insert)
    {
        $this->firstname = 'Sanjar';
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->firstname = 'Bahrom';
        parent::afterFind(); // TODO: Change the autogenerated stub
    }


}